language: node_js
node_js:
  - 7
  - 6
  - 5
  - 4

cache:
  directories:
  - node_modules

script:
  - ./node_modules/.bin/babel ./src --out-dir ./dist

deploy:
  - provider: npm
    email: "ainun@nazieb.com"
    api_key:
      secure: "mVhkapgw+6ik06jzx63XWPoxNRlbXEHqk4nPn8WwoyyTDAoe6x1cTRlq2TbIQ/7MycNMk06ZlZzst7UnyDdW9LzVdDqYMDeobwi3SctPA4wjCMvnkK+yGYHyxm3xASfsg8h03QMZWVFxD2hlY+RCVVZyUQvuGzuINBnK+vFOY3vy+MRHCFYAX7QfDv3Z6n46dVc1ReNDBDTV+zfGOYepniZvK9oxwOoeKTZgGihlGaJZqD3ROOigx9S7WAqPKJYTpwGkr8i+OctYkozBWCB5BPSV3qZQ8y0qdGVVtwEFI7PtNb3tts+TPn7v16+d3yLw1S/cSbn7Jtr7iw7kdfPBURnu4tTjFEzbqYSbtMYw+OfJBluKadsslmpRTbmEqrsZNByHYjZqFfpyRgIGK7yWbbvxXiGXBKYR5It8zzzcE5KWwN81Uy0buwW7n3zHsjlGIufC5Mxcs4WQrbqI2M1yzo6YuivMabQsmyRYyyelEFtLGLVw9dpa9RGkZLQaiUhOt4uYjY0pIZvblxspxg41QkjxQO13HEoXPny8owk9X0gpe3zMznzNBlo4RpMhAiQiwnLzhZUiOUfnjktpWEs/NkC8R49uVnoKmzOAVlLlkOfdqbRHdsqk7jqZTIqxNWLpK0DSCXB38VF0RtajEfvINo7Y8LYBpy/WUlarv5AqHVw="
    on:
      tags: true
    skip_cleanup: true